// SPDX-License-Identifier: Apache-2.0
package us.nimbusxr.axx.idea;

import com.intellij.execution.ExecutionListener;
import com.intellij.execution.RunManager;
import com.intellij.execution.RunnerAndConfigurationSettings;
import com.intellij.execution.executors.DefaultDebugExecutor;
import com.intellij.execution.process.ProcessEvent;
import com.intellij.execution.process.ProcessHandler;
import com.intellij.execution.process.ProcessListener;
import com.intellij.execution.process.ProcessOutputType;
import com.intellij.execution.runners.ExecutionEnvironment;
import com.intellij.execution.runners.ExecutionUtil;
import com.intellij.execution.ui.RunContentDescriptor;
import com.intellij.execution.ui.RunContentManager;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.Key;

import org.jetbrains.annotations.NotNull;

import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Starts the debugger run configurations an axx run asks for, the moment it asks.
 *
 * <p>The axx runner prints a {@code [AXX-IDE] debug-listener-request ...} or {@code [AXX-IDE]
 * debug-attach-request ...} line when it starts an application in debug mode (see {@link
 * DebugRequest}). This listener watches the console of every process, whichever executor started it
 * (axx usually runs from the {@code "axx: debug"} Shell Script configuration with Run). When a
 * request appears, it starts the matching {@code "Debugger: <app>"} run configuration, generated by
 * {@code axx ide intellij}, with the Debug executor, unless that configuration is already starting
 * or running. When the process that asked ends, the debuggers this plugin started for it are
 * stopped again.
 *
 * <p>The plugin only reacts to explicit requests, so running anything else starts nothing, and only
 * the applications a run actually launches get a debugger.
 *
 * <p>This is a project listener: its registry receives all of the project's execution events.
 */
public class DebugAutoStartListener implements ExecutionListener {

    private static final Logger LOG = Logger.getInstance(DebugAutoStartListener.class);

    private final DebuggerRegistry debuggers = new DebuggerRegistry();

    @Override
    public void processStartScheduled(
            @NotNull String executorId, @NotNull ExecutionEnvironment env) {
        debuggers.launchScheduled(env.getRunProfile().getName(), env);
    }

    @Override
    public void processNotStarted(@NotNull String executorId, @NotNull ExecutionEnvironment env) {
        debuggers.launchEnded(env.getRunProfile().getName(), env);
    }

    @Override
    public void processTerminated(
            @NotNull String executorId,
            @NotNull ExecutionEnvironment env,
            @NotNull ProcessHandler handler,
            int exitCode) {
        debuggers.launchEnded(env.getRunProfile().getName(), env);
    }

    @Override
    public void processStarted(
            @NotNull String executorId,
            @NotNull ExecutionEnvironment env,
            @NotNull ProcessHandler handler) {
        // Debugger configurations are never watched (including the ones this class starts).
        // Matching by name keeps the plugin free of per-language plugin dependencies: they may
        // be Java Remote, Node.js, Python or Go configurations.
        if (DebuggerRegistry.shouldWatch(executorId, env.getRunProfile().getName())) {
            handler.addProcessListener(new RequestWatcher(env.getProject(), debuggers));
        }
    }

    /** Watches one process's output and owns the debuggers started for it. */
    private static final class RequestWatcher implements ProcessListener {
        private final Project project;
        private final DebuggerRegistry debuggers;
        // Output streams arrive on separate reader threads; each gets its own buffer.
        private final Map<String, LineBuffer> buffers = new ConcurrentHashMap<>();
        private final Set<String> startedByUs = ConcurrentHashMap.newKeySet();

        RequestWatcher(Project project, DebuggerRegistry debuggers) {
            this.project = project;
            this.debuggers = debuggers;
        }

        @Override
        public void onTextAvailable(@NotNull ProcessEvent event, @NotNull Key outputType) {
            String text = event.getText();
            if (text == null) {
                return;
            }
            LineBuffer buffer =
                    buffers.computeIfAbsent(streamOf(outputType), k -> new LineBuffer());
            synchronized (buffer) {
                for (String line : buffer.append(text)) {
                    DebugRequest request = DebugRequest.parse(line);
                    if (request != null) {
                        start(request);
                    }
                }
            }
        }

        @Override
        public void processTerminated(@NotNull ProcessEvent event) {
            stopDebuggers();
        }

        private void start(DebugRequest request) {
            ApplicationManager.getApplication()
                    .invokeLater(
                            () -> {
                                if (!project.isDisposed()) {
                                    startOnEdt(request);
                                }
                            });
        }

        private void startOnEdt(DebugRequest request) {
            String name = request.configurationName();
            long now = System.currentTimeMillis();
            // Already starting or running, for example started by the "axx: debug all" compound.
            if (debuggers.isLive(name, now) || isRunning(project, name)) {
                return;
            }
            RunnerAndConfigurationSettings settings =
                    RunManager.getInstance(project).findConfigurationByName(name);
            if (settings == null) {
                LOG.warn(
                        "axx requested debugger '"
                                + name
                                + "' but no such run configuration exists. Run `axx ide intellij`"
                                + " to generate it.");
                return;
            }
            LOG.info("axx: starting debugger '" + name + "' (" + request.kind() + ")");
            debuggers.startRequested(name, now);
            startedByUs.add(name);
            ExecutionUtil.runConfiguration(
                    settings, DefaultDebugExecutor.getDebugExecutorInstance());
        }

        private void stopDebuggers() {
            if (startedByUs.isEmpty()) {
                return;
            }
            ApplicationManager.getApplication()
                    .invokeLater(
                            () -> {
                                if (project.isDisposed()) {
                                    return;
                                }
                                for (RunContentDescriptor descriptor :
                                        RunContentManager.getInstance(project)
                                                .getAllDescriptors()) {
                                    if (startedByUs.contains(descriptor.getDisplayName())) {
                                        stop(descriptor);
                                    }
                                }
                                startedByUs.clear();
                            });
        }

        private static void stop(RunContentDescriptor descriptor) {
            ProcessHandler handler = descriptor.getProcessHandler();
            if (handler == null || handler.isProcessTerminated()) {
                return;
            }
            LOG.info("axx: stopping debugger '" + descriptor.getDisplayName() + "'");
            // What the Stop button does: remote debug sessions detach, leaving the application's
            // lifecycle to the axx runner.
            if (handler.detachIsDefault()) {
                handler.detachProcess();
            } else {
                handler.destroyProcess();
            }
        }

        private static String streamOf(Key<?> outputType) {
            if (ProcessOutputType.isStderr(outputType)) {
                return "stderr";
            }
            return ProcessOutputType.isStdout(outputType) ? "stdout" : "system";
        }
    }

    /** Whether a configuration has a live process in the Run or Debug tool window. */
    private static boolean isRunning(Project project, String configurationName) {
        for (RunContentDescriptor descriptor :
                RunContentManager.getInstance(project).getAllDescriptors()) {
            ProcessHandler handler = descriptor.getProcessHandler();
            if (configurationName.equals(descriptor.getDisplayName())
                    && handler != null
                    && !handler.isProcessTerminated()) {
                return true;
            }
        }
        return false;
    }
}
