import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// Pages generated by `npm run gen` live under references/_gen/ (gitignored) and
// carry a `slug` that publishes them at their natural URLs, for example
// references/_gen/steps/mock.md at /references/steps/mock/.
export const collections = {
	docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
