package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/nimbusxr/axx/examples/parcels/app/graph/model"
)

// FindParcelByReference is the resolver for the findParcelByReference field.
func (r *entityResolver) FindParcelByReference(ctx context.Context, reference string) (*model.Parcel, error) {
	return r.Parcels.Parcel(ctx, reference)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
