package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/nimbusxr/axx/examples/parcels/app/graph/model"
)

// HoldParcel is the resolver for the holdParcel field.
func (r *mutationResolver) HoldParcel(ctx context.Context, reference string, until string, reason *string) (*model.Parcel, error) {
	p, err := r.Parcels.Hold(ctx, reference, until, reason)
	return p, graphError(reference, err)
}

// Parcel is the resolver for the parcel field.
func (r *queryResolver) Parcel(ctx context.Context, reference string) (*model.Parcel, error) {
	return r.Parcels.Parcel(ctx, reference)
}

// ParcelScanned is the resolver for the parcelScanned field.
func (r *subscriptionResolver) ParcelScanned(ctx context.Context, reference string) (<-chan *model.Scan, error) {
	scans, err := r.Parcels.Scans(ctx, reference)
	return scans, graphError(reference, err)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
