// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Mutation struct {
}

type Parcel struct {
	Reference    string       `json:"reference"`
	Status       string       `json:"status"`
	ServiceLevel ServiceLevel `json:"serviceLevel"`
	WeightGrams  int          `json:"weightGrams"`
	// The day its depot holds it until.
	HeldUntil *string `json:"heldUntil,omitempty"`
	// The latest scan; null before the first.
	LastScan *Scan `json:"lastScan,omitempty"`
	// The shop that sends it.
	Shop *Shop `json:"shop"`
}

func (Parcel) IsEntity() {}

// The parcels subgraph: a parcel's status, holding it at its depot, and its
// scans as they happen. The shops subgraph resolves a parcel's shop.
type Query struct {
}

type Scan struct {
	Reference string  `json:"reference"`
	Status    string  `json:"status"`
	Location  *string `json:"location,omitempty"`
	ScannedAt *string `json:"scannedAt,omitempty"`
}

// A shop, which the shops subgraph describes.
type Shop struct {
	ID string `json:"id"`
}

func (Shop) IsEntity() {}

type Subscription struct {
}

type ServiceLevel string

const (
	ServiceLevelStandard ServiceLevel = "STANDARD"
	ServiceLevelExpress  ServiceLevel = "EXPRESS"
)

var AllServiceLevel = []ServiceLevel{
	ServiceLevelStandard,
	ServiceLevelExpress,
}

func (e ServiceLevel) IsValid() bool {
	switch e {
	case ServiceLevelStandard, ServiceLevelExpress:
		return true
	}
	return false
}

func (e ServiceLevel) String() string {
	return string(e)
}

func (e *ServiceLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceLevel", str)
	}
	return nil
}

func (e ServiceLevel) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
