package fixtures

import (
	"context"
	"os"
	"os/exec"
	"strings"
	"testing"
)

// Opt-in ignored outputs: generated files become gitignored derivations with
// exact, tool-maintained .gitignore entries; the hand-edit guard keeps
// working through the manifest; clean deletes them and untrack takes them out
// of the git index.

func ignoredWorkspace(t *testing.T) *workspace {
	t.Helper()
	w := notesWorkspace(t)
	w.write("kafka/notes/notes.factory.yaml", `factory:
  family: avro
  schema: ../../schemas/note.avsc
  output: { ignored: true }
prototype:
  text: "hello"
identity:
  - path: note_id
    prefix: note-
`)
	w.write("kafka/notes/briefing.fixture.yaml", "# pure\n")
	w.write("kafka/notes/debrief.fixture.yaml", "data: { text: \"bye\" }\n")
	w.write("kafka/memos/memos.factory.yaml", `factory:
  family: avro
  schema: ../../schemas/note.avsc
prototype:
  text: "memo"
identity:
  - path: note_id
    prefix: memo-
fixtures:
  memo-1: {}
`)
	return w
}

func TestIgnoredFactoryGetsExactGitignoreEntries(t *testing.T) {
	w := ignoredWorkspace(t)
	w.generate()
	gi := w.read("kafka/notes/.gitignore")
	mustContain(t, gi, "GENERATED by axx fixtures", "/briefing.json", "/debrief.json")
	if strings.Contains(gi, "*") || strings.Contains(gi, "fixture.yaml") {
		t.Errorf("exact paths only, never sources:\n%s", gi)
	}
	if w.exists("kafka/memos/.gitignore") {
		t.Error("committed neighbors get no .gitignore")
	}
	if !w.exists("kafka/notes/briefing.json") {
		t.Error("ignored outputs still materialize")
	}
}

func TestIgnoredModuleDefaultAndPerFactoryOverride(t *testing.T) {
	w := ignoredWorkspace(t)
	w.cfg.OutputIgnored = true
	w.replace("kafka/notes/notes.factory.yaml", "output: { ignored: true }", "output: { ignored: false }")
	w.generate()
	if w.exists("kafka/notes/.gitignore") || !w.exists("kafka/memos/.gitignore") {
		t.Error("the factory override wins over the module default")
	}
}

func TestManagedGitignoreIsDriftCheckedAndHandEditsRefused(t *testing.T) {
	w := ignoredWorkspace(t)
	w.generate()
	if f := w.check(); len(f) != 0 {
		t.Fatalf("check: %v", f)
	}
	w.write("kafka/notes/.gitignore", w.read("kafka/notes/.gitignore")+"/something-else.json\n")
	mustErrContain(t, w.generateErr(), "hand-edited", ".gitignore")
}

func TestHandEditGuardOnIgnoredOutputsWorksWithoutGit(t *testing.T) {
	w := ignoredWorkspace(t)
	w.generate()
	w.replace("kafka/notes/debrief.json", "bye", "tampered")
	mustErrContain(t, w.generateErr(), "hand-edited", "debrief.json")
}

func TestMissingIgnoredOutputFailsWithMaterializationGuidance(t *testing.T) {
	w := ignoredWorkspace(t)
	w.generate()
	w.remove("kafka/notes/briefing.json")
	f := w.check()
	if len(f) != 1 {
		t.Fatalf("failures: %v", f)
	}
	mustContain(t, f[0], "briefing.json", "materialized", "axx fixtures generate")
	w.generate()
	if f := w.check(); len(f) != 0 {
		t.Errorf("regenerate heals: %v", f)
	}
}

func TestFlippingBackToCommittedOrphansTheGitignore(t *testing.T) {
	w := ignoredWorkspace(t)
	w.generate()
	w.replace("kafka/notes/notes.factory.yaml", "output: { ignored: true }", "output: { ignored: false }")
	found := false
	for _, f := range w.check() {
		found = found || strings.Contains(f, "orphan") && strings.Contains(f, ".gitignore")
	}
	if !found {
		t.Errorf("no orphan: %v", w.check())
	}
	w.generate()
	if f := w.check(); len(f) != 0 {
		t.Errorf("check: %v", f)
	}
	if !w.exists("kafka/notes/.gitignore") {
		t.Error("the leftover file is unmanaged, never deleted")
	}
}

func TestMultiFileFamilyGitignoreEntriesAreSubdirRelative(t *testing.T) {
	w := ignoredWorkspace(t)
	w.write("seeds/pong.factory.yaml", `factory:
  family: dataset
  options: { format: csv }
  output: { ignored: true }
prototype:
  axx.orders:
    state: NEW
fixtures:
  ping-pong:
    axx.orders:
      - id: order-1
`)
	w.generate()
	mustContain(t, w.read("seeds/.gitignore"), "/ping-pong/axx.orders.csv", "/ping-pong/table-ordering.txt")
}

// cleanupWorkspace has one ignored avro factory, one ignored CSV dataset
// (multi-file, subdirectory) and one committed factory.
func cleanupWorkspace(t *testing.T) *workspace {
	t.Helper()
	w := notesWorkspace(t)
	w.write("kafka/notes/notes.factory.yaml", `factory:
  family: avro
  schema: ../../schemas/note.avsc
  output: { ignored: true }
prototype:
  text: "hello"
identity:
  - path: note_id
    prefix: note-
fixtures:
  briefing: {}
`)
	w.write("seeds/orders.factory.yaml", `factory:
  family: dataset
  options: { format: csv }
  output: { ignored: true }
fixtures:
  order-batch:
    axx.orders:
      - id: order-1
        state: NEW
`)
	w.write("kafka/memos/memos.factory.yaml", `factory:
  family: avro
  schema: ../../schemas/note.avsc
prototype:
  text: "memo"
identity:
  - path: note_id
    prefix: memo-
fixtures:
  memo-1: {}
`)
	return w
}

func TestCleanDeletesIgnoredOutputsOnly(t *testing.T) {
	w := cleanupWorkspace(t)
	w.generate()
	if !w.exists("kafka/notes/briefing.json") || !w.exists("seeds/order-batch/axx.orders.csv") {
		t.Fatal("outputs missing")
	}
	dry, err := w.mustGenerator().Clean(true)
	if err != nil {
		t.Fatal(err)
	}
	if len(dry.Deleted) != 3 || !w.exists("kafka/notes/briefing.json") {
		t.Fatalf("dry run: %+v", dry)
	}
	res, err := w.mustGenerator().Clean(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Deleted) != 3 || len(res.SkippedCommitted) != 1 || res.SkippedCommitted[0] != "kafka/memos/memo-1.json" {
		t.Fatalf("result: %+v", res)
	}
	for rel, want := range map[string]bool{
		"kafka/notes/briefing.json": false, "seeds/order-batch": false, "kafka/memos/memo-1.json": true,
		"kafka/notes/.gitignore": true, "kafka/notes/notes.factory.yaml": true, ManifestFile: true,
	} {
		if w.exists(rel) != want {
			t.Errorf("%s exists = %v, want %v", rel, !want, want)
		}
	}
	found := false
	for _, f := range w.check() {
		found = found || strings.Contains(f, "materialized")
	}
	if !found {
		t.Error("the cleaned state is the fresh-clone state")
	}
	w.generate()
	if f := w.check(); len(f) != 0 {
		t.Errorf("generate heals: %v", f)
	}
}

func git(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GIT_CONFIG_GLOBAL=/dev/null", "GIT_CONFIG_SYSTEM=/dev/null")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
	return string(out)
}

func TestUntrackStagesGitRmCachedForTrackedIgnoredOutputsOnly(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not installed")
	}
	w := cleanupWorkspace(t)
	w.generate()
	git(t, w.dir, "init", "--quiet")
	git(t, w.dir, "config", "user.email", "test@example.com")
	git(t, w.dir, "config", "user.name", "Test")
	git(t, w.dir, "add", "--force", ".")
	git(t, w.dir, "commit", "--quiet", "-m", "pre-adoption state")

	dry, err := w.mustGenerator().Untrack(context.Background(), true)
	if err != nil {
		t.Fatal(err)
	}
	if len(dry.Untracked) != 3 || git(t, w.dir, "ls-files", "--", "kafka/notes/briefing.json") == "" {
		t.Fatalf("dry run touched the index: %+v", dry)
	}
	res, err := w.mustGenerator().Untrack(context.Background(), false)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Untracked) != 3 || res.AlreadyUntracked != 0 {
		t.Fatalf("result: %+v", res)
	}
	if strings.TrimSpace(git(t, w.dir, "ls-files", "--", "kafka/notes/briefing.json")) != "" || !w.exists("kafka/notes/briefing.json") {
		t.Error("untracked but still on disk")
	}
	for _, kept := range []string{"kafka/memos/memo-1.json", "kafka/notes/.gitignore"} {
		if strings.TrimSpace(git(t, w.dir, "ls-files", "--", kept)) == "" {
			t.Errorf("%s must stay tracked", kept)
		}
	}
	again, err := w.mustGenerator().Untrack(context.Background(), false)
	if err != nil {
		t.Fatal(err)
	}
	if len(again.Untracked) != 0 || again.AlreadyUntracked != 3 {
		t.Errorf("idempotent: %+v", again)
	}
}

func TestUntrackOutsideAGitWorkTreeFails(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not installed")
	}
	w := cleanupWorkspace(t)
	w.generate()
	t.Setenv("GIT_CEILING_DIRECTORIES", w.dir)
	_, err := w.mustGenerator().Untrack(context.Background(), false)
	mustErrContain(t, err, "git")
	if codeOf(err) != CodeGit {
		t.Errorf("code: %s", codeOf(err))
	}
}
