package fixtures

import (
	"sort"

	"github.com/nimbusxr/axx/internal/compat/jyaml"
)

const lintHeader = "# GENERATED by axx fixtures - do not edit.\n" +
	"# Rules are derived from the identity: declarations in the factory specs;\n" +
	"# regenerate with `axx fixtures generate`.\n" +
	"# Wired in via axx.yaml: lint.include: [axx-lint.generated.yaml]\n"

// wildcardIndices widens fixed indices to wildcards: an identity names one
// element (payments[0].id) but the lint must cover every element.
func wildcardIndices(path string) string {
	return indexRE.ReplaceAllString(path, "[*]")
}

func lintFilePatterns(f Family, spec *Spec) []string {
	if r, ok := f.(LintRuler); ok {
		return r.LintFilePatterns(spec)
	}
	var out []string
	for _, dir := range spec.OutputDirs() {
		if dir == "" {
			out = append(out, "*.json")
		} else {
			out = append(out, dir+"/*.json")
		}
	}
	return out
}

func lintJSONPath(f Family, spec *Spec, identityPath string) string {
	if r, ok := f.(LintRuler); ok {
		return r.LintJSONPath(spec, identityPath)
	}
	return identityPath
}

// emitLintRules renders the generated lint rules: one structural
// cross-file-unique rule per identity, covering the whole output directory so
// hand-written neighbors are linted too. It returns nil when no factory
// declares identities (or every family opts out).
func emitLintRules(specs []*Spec, familyOf func(*Spec) (Family, error)) ([]byte, error) {
	sorted := append([]*Spec(nil), specs...)
	sort.SliceStable(sorted, func(i, j int) bool { return javaCompare(sorted[i].SourceName, sorted[j].SourceName) < 0 })
	var rules []any
	for _, spec := range sorted {
		f, err := familyOf(spec)
		if err != nil {
			return nil, err
		}
		patterns := lintFilePatterns(f, spec)
		if len(patterns) == 0 {
			continue // a non-JSON family opted out of structural rules
		}
		for _, id := range spec.Identity {
			jsonPath := lintJSONPath(f, spec, id.Path)
			if jsonPath == "" {
				continue
			}
			ps := make([]any, len(patterns))
			for i, p := range patterns {
				ps[i] = p
			}
			rules = append(rules, newObject(
				"name", spec.SourceName+": "+id.Path+" uniqueness",
				"filePatterns", ps,
				"type", "jsonpath",
				"jsonPath", wildcardIndices(jsonPath),
				"description", "Identity declared by "+spec.SourceName+"; every fixture in the directory must own a unique value",
				"validation", "cross-file-unique",
			))
		}
	}
	if len(rules) == 0 {
		return nil, nil
	}
	out, err := jyaml.Marshal(newObject("rules", rules), yamlManifest)
	if err != nil {
		return nil, err
	}
	return append([]byte(lintHeader), out...), nil
}
