package fixtures

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"

	"github.com/nimbusxr/axx/internal/compat/jsonx"
	"github.com/nimbusxr/axx/internal/compat/jyaml"
)

const manifestHeader = "# GENERATED by axx fixtures - the ownership list. Only files recorded here are\n" +
	"# ever touched by the tool; a managed file whose content no longer matches its\n" +
	"# sha256 is a refused hand-edit.\n"

// ManifestEntry records one managed file.
type ManifestEntry struct {
	Path    string `json:"path"`
	SHA256  string `json:"sha256"`
	Factory string `json:"factory"`
	Fixture string `json:"fixture"`
}

// Manifest is the committed record of which files the factory manages:
// managed path (relative to the resource root) to content hash, owning
// factory and fixture key. It is what makes partial adoption safe (only
// recorded files are ever touched) and hand-edits detectable.
type Manifest struct {
	entries map[string]ManifestEntry
}

// NewManifest returns an empty manifest.
func NewManifest() *Manifest { return &Manifest{entries: map[string]ManifestEntry{}} }

// SHA256 is the lowercase hex SHA-256 of content.
func SHA256(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}

// Put records path with the hash of content.
func (m *Manifest) Put(path string, content []byte, factory, fixture string) {
	m.entries[path] = ManifestEntry{Path: path, SHA256: SHA256(content), Factory: factory, Fixture: fixture}
}

// PutEntry records an entry as is.
func (m *Manifest) PutEntry(e ManifestEntry) { m.entries[e.Path] = e }

// Get returns the entry for path.
func (m *Manifest) Get(path string) (ManifestEntry, bool) {
	e, ok := m.entries[path]
	return e, ok
}

// Managed reports whether path is recorded.
func (m *Manifest) Managed(path string) bool {
	_, ok := m.entries[path]
	return ok
}

// Entries returns every entry in path order (Java String order).
func (m *Manifest) Entries() []ManifestEntry {
	paths := make([]string, 0, len(m.entries))
	for p := range m.entries {
		paths = append(paths, p)
	}
	sortStrings(paths)
	out := make([]ManifestEntry, len(paths))
	for i, p := range paths {
		out[i] = m.entries[p]
	}
	return out
}

// Len is the number of entries.
func (m *Manifest) Len() int { return len(m.entries) }

// LoadManifest reads baseDir's manifest; a missing file is an empty one.
func LoadManifest(baseDir string) (*Manifest, error) {
	path := filepath.Join(baseDir, ManifestFile)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return NewManifest(), nil
	}
	if err != nil {
		return nil, ioError(err, "cannot read %s", path)
	}
	m, err := ParseManifest(data)
	if err != nil {
		return nil, specError("cannot parse %s: %s", path, errText(err))
	}
	return m, nil
}

// ParseManifest reads manifest bytes.
func ParseManifest(data []byte) (*Manifest, error) {
	m := NewManifest()
	root, err := jyaml.Unmarshal(data)
	if err != nil {
		return nil, err
	}
	doc, ok := root.(*jsonx.Object)
	if root == nil {
		return m, nil
	}
	if !ok {
		return nil, specError("expected a mapping")
	}
	for _, k := range doc.Keys() {
		if k != "files" {
			return nil, specError("unknown field %q", k)
		}
	}
	list, ok := get(doc, "files").([]any)
	if !ok && get(doc, "files") != nil {
		return nil, specError("files: must be a list")
	}
	for _, item := range list {
		entry, ok := item.(*jsonx.Object)
		if !ok {
			return nil, specError("files: entries must be mappings")
		}
		for _, k := range entry.Keys() {
			switch k {
			case "path", "sha256", "factory", "fixture":
			default:
				return nil, specError("files: unknown field %q", k)
			}
		}
		e := ManifestEntry{
			Path: text(get(entry, "path")), SHA256: text(get(entry, "sha256")),
			Factory: text(get(entry, "factory")), Fixture: text(get(entry, "fixture")),
		}
		m.entries[e.Path] = e
	}
	return m, nil
}

// text renders a scalar as a String field would receive it; nil stays "".
func text(v any) string {
	if v == nil {
		return ""
	}
	return valueOf(v)
}

// Bytes renders the manifest canonically.
func (m *Manifest) Bytes() []byte {
	files := make([]any, 0, len(m.entries))
	for _, e := range m.Entries() {
		files = append(files, newObject("path", e.Path, "sha256", e.SHA256, "factory", e.Factory, "fixture", e.Fixture))
	}
	out, err := jyaml.Marshal(newObject("files", files), yamlManifest)
	if err != nil {
		panic(err)
	}
	return append([]byte(manifestHeader), out...)
}

// Write stores the manifest in baseDir.
func (m *Manifest) Write(baseDir string) error {
	path := filepath.Join(baseDir, ManifestFile)
	if err := os.WriteFile(path, m.Bytes(), 0o644); err != nil {
		return ioError(err, "cannot write manifest %s", path)
	}
	return nil
}
