package fixtures

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/nimbusxr/axx/internal/compat/jsonx"
	"github.com/nimbusxr/axx/internal/compat/jyaml"
)

const pairingsHeader = "# GENERATED by axx fixtures - do not edit.\n" +
	"# Recorded expression-function results (function version + args -> value).\n" +
	"# `axx fixtures check` reads only this file; regenerate with your local stack\n" +
	"# up to record new pairings.\n"

// yamlFactory is the rendering of the dataset and yaml families, adopted
// specs and the pairings lock: minimized quotes, numeric-looking strings
// quoted, no document start marker.
var yamlFactory = jyaml.Options{MinimizeQuotes: true, QuoteNumericStrings: true}

// yamlManifest renders the manifest and the generated lint rules.
var yamlManifest = jyaml.Options{MinimizeQuotes: true}

type recorded struct {
	version  string
	order    []string // argument keys in recording order
	pairings map[string]pairing
}

type pairing struct {
	args  []string
	value string
}

// pairingsLock is the committed record of recorded-function results
// (PairingsLock).
type pairingsLock struct {
	functions map[string]*recorded
}

func newPairingsLock() *pairingsLock { return &pairingsLock{functions: map[string]*recorded{}} }

func argsKey(args []string) string { return strings.Join(args, "\x00") + "\x00" }

func (p *pairingsLock) recordedVersion(function string) (string, bool) {
	r, ok := p.functions[function]
	if !ok {
		return "", false
	}
	return r.version, true
}

func (p *pairingsLock) lookup(function string, args []string) (string, bool) {
	r, ok := p.functions[function]
	if !ok {
		return "", false
	}
	pr, ok := r.pairings[argsKey(args)]
	return pr.value, ok
}

func (p *pairingsLock) record(function, version string, args []string, value string) {
	r, ok := p.functions[function]
	if !ok {
		r = &recorded{version: version, pairings: map[string]pairing{}}
		p.functions[function] = r
	}
	k := argsKey(args)
	if _, seen := r.pairings[k]; !seen {
		r.order = append(r.order, k)
	}
	r.pairings[k] = pairing{args: append([]string(nil), args...), value: value}
}

func (p *pairingsLock) empty() bool { return len(p.functions) == 0 }

// loadPairings reads the lock from baseDir; a missing file is an empty lock.
func loadPairings(baseDir string) (*pairingsLock, error) {
	lock := newPairingsLock()
	path := filepath.Join(baseDir, PairingsFile)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return lock, nil
	}
	if err != nil {
		return nil, ioError(err, "cannot read %s", path)
	}
	root, err := jyaml.Unmarshal(data)
	if err != nil {
		return nil, specError("cannot parse %s: %v", path, err)
	}
	doc, ok := root.(*jsonx.Object)
	if root == nil {
		return lock, nil
	}
	if !ok {
		return nil, specError("cannot parse %s: expected a mapping of function names", path)
	}
	for _, function := range doc.Keys() {
		body, _ := get(doc, function).(*jsonx.Object)
		version := valueOf(get(body, "version"))
		list, _ := get(body, "pairings").([]any)
		for _, e := range list {
			entry, ok := e.(*jsonx.Object)
			if !ok {
				continue
			}
			rawArgs, _ := get(entry, "args").([]any)
			args := make([]string, len(rawArgs))
			for i, a := range rawArgs {
				args[i] = valueOf(a)
			}
			lock.record(function, version, args, valueOf(get(entry, "value")))
		}
	}
	return lock, nil
}

func compareArgs(a, b []string) int {
	for i := 0; i < len(a) && i < len(b); i++ {
		if c := javaCompare(a[i], b[i]); c != 0 {
			return c
		}
	}
	return len(a) - len(b)
}

// serialize renders the lock canonically: functions by name, pairings by
// their argument lists.
func (p *pairingsLock) serialize() []byte {
	names := make([]string, 0, len(p.functions))
	for n := range p.functions {
		names = append(names, n)
	}
	sortStrings(names)
	doc := jsonx.NewObject()
	for _, n := range names {
		r := p.functions[n]
		list := make([]pairing, 0, len(r.order))
		for _, k := range r.order {
			list = append(list, r.pairings[k])
		}
		sort.SliceStable(list, func(i, j int) bool { return compareArgs(list[i].args, list[j].args) < 0 })
		pairs := make([]any, len(list))
		for i, pr := range list {
			args := make([]any, len(pr.args))
			for j, a := range pr.args {
				args[j] = a
			}
			pairs[i] = newObject("args", args, "value", pr.value)
		}
		doc.Set(n, newObject("version", r.version, "pairings", pairs))
	}
	out, err := jyaml.Marshal(doc, yamlFactory)
	if err != nil {
		panic(err) // the document holds only strings, lists and maps
	}
	return append([]byte(pairingsHeader), out...)
}
