// Package md renders axx's generated reference documentation as Markdown.
//
// The same renderer feeds the documentation site, the agent skills and
// `axx steps --format md`, so they can never disagree. Every renderer
// returns an error rather than empty output: an empty step reference is a
// bug, not a valid document.
package md

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/nimbusxr/axx/core"
	"github.com/nimbusxr/axx/internal/match"
)

// GeneratedHeader marks generated files; CI fails when they drift.
const GeneratedHeader = "<!-- Code generated by `axx docs export`. DO NOT EDIT. -->\n"

// ErrEmpty is returned when a renderer would produce an empty document.
var ErrEmpty = errors.New("refusing to render an empty reference")

// PackInfo describes a pack for rendering.
type PackInfo struct {
	Name     string
	Manifest core.Manifest
	// Builtin is set for the core, which every project has.
	Builtin bool
}

// StepsPage renders the reference page for one pack.
func StepsPage(reg *match.Registry, p PackInfo, frontmatter bool) (string, error) {
	defs := defsOf(reg, p.Name)
	if len(defs) == 0 {
		return "", fmt.Errorf("pack %s: %w", p.Name, ErrEmpty)
	}
	var b strings.Builder
	if frontmatter {
		fmt.Fprintf(&b, "---\ntitle: %s steps\ndescription: %q\n---\n\n", p.Name, oneLine(p.Manifest.Doc))
	}
	b.WriteString(GeneratedHeader)
	if !frontmatter {
		fmt.Fprintf(&b, "\n# %s steps\n", p.Name)
	}
	if p.Manifest.Doc != "" {
		fmt.Fprintf(&b, "\n%s\n", strings.TrimSpace(p.Manifest.Doc))
	}
	// The page's steps first, one line each: a reader (or an agent reading
	// the top of the file) finds the one it needs, then its section by id.
	b.WriteString("\nThe steps, each documented below under its id:\n\n")
	for _, d := range defs {
		fmt.Fprintf(&b, "- `%s`: `%s`\n", d.Step.ID, d.Step.Expr)
	}
	variants := variantsByDef(reg)
	params := paramDocs(reg)
	for _, d := range defs {
		writeStep(&b, "##", d, variants[d], params)
	}
	return b.String(), nil
}

func writeStep(b *strings.Builder, heading string, d *match.Def, variants []string, params map[string]core.ParamType) {
	s := d.Step
	fmt.Fprintf(b, "\n%s `%s`\n\n", heading, s.ID)
	if s.DeprecatedBy != "" {
		fmt.Fprintf(b, "> **Deprecated:** %s\n\n", s.DeprecatedBy)
	}
	kw := s.Keyword
	if kw == "" {
		kw = "*"
	}
	fmt.Fprintf(b, "```gherkin\n%s %s\n", kw, s.Expr)
	switch s.Arg {
	case core.ArgTable:
		if s.Table != nil && len(s.Table.Columns) > 0 {
			fmt.Fprintf(b, "  | %s |\n", strings.Join(s.Table.Columns, " | "))
		} else {
			b.WriteString("  | ... | ... |\n")
		}
	case core.ArgDocString:
		b.WriteString("  \"\"\"\n  ...\n  \"\"\"\n")
	}
	b.WriteString("```\n")
	if s.Arg == core.ArgTable && s.Table != nil && len(s.Table.Columns) > 1 {
		b.WriteString("\nThe table may start with the row naming its columns, as above, or go straight to its rows.\n")
	}
	if s.Doc != "" {
		fmt.Fprintf(b, "\n%s\n", strings.TrimSpace(s.Doc))
	}
	writeParams(b, d, params)
	if s.Table != nil {
		writeTable(b, s.Table)
	}
	if len(variants) > 1 {
		b.WriteString("\n**Variants**, the parts in `[[...]]` said or left out:\n\n")
		for _, v := range variants {
			fmt.Fprintf(b, "- `%s`\n", v)
		}
	}
	if len(s.Examples) > 0 {
		b.WriteString("\n**Example:**\n\n```gherkin\n")
		for _, ex := range s.Examples {
			b.WriteString(ex + "\n")
		}
		b.WriteString("```\n")
	}
	if s.Since != "" {
		fmt.Fprintf(b, "\n_Since %s._\n", s.Since)
	}
}

// writeParams is a step's parameters: what each takes, the values it takes
// when it takes one of a set, and a value it takes.
func writeParams(b *strings.Builder, d *match.Def, params map[string]core.ParamType) {
	seen := map[string]bool{}
	var used []core.ParamType
	values := false
	for _, n := range d.Names {
		if !seen[n] {
			seen[n] = true
			p := params[n]
			p.Name = n
			used = append(used, p)
			values = values || len(p.Values) > 0
		}
	}
	if len(used) == 0 {
		return
	}
	b.WriteString("\n| Parameter | Takes |")
	if values {
		b.WriteString(" Values |")
	}
	b.WriteString(" For example |\n|---|---|")
	if values {
		b.WriteString("---|")
	}
	b.WriteString("---|\n")
	for _, p := range used {
		fmt.Fprintf(b, "| `{%s}` | %s |", p.Name, escapePipes(strings.TrimSuffix(oneLine(p.Doc), ".")))
		if values {
			fmt.Fprintf(b, " %s |", escapePipes(codes(p.Values)))
		}
		fmt.Fprintf(b, " %s |\n", escapePipes(codes(first(p.Examples, 2))))
	}
}

// writeTable is what a step's table holds: the rows it knows, what each
// takes, the values it takes when it takes one of a set, and its default,
// or that the table must have it.
func writeTable(b *strings.Builder, t *core.TableDoc) {
	if len(t.Rows) > 0 {
		name := "Row"
		if len(t.Columns) > 0 {
			name = strings.ToUpper(t.Columns[0][:1]) + t.Columns[0][1:]
		}
		values, defaults := false, false
		for _, r := range t.Rows {
			values = values || len(r.Values) > 0
			defaults = defaults || r.Default != "" || r.Required
		}
		fmt.Fprintf(b, "\n| %s | Takes |", name)
		sep := "\n|---|---|"
		if values {
			b.WriteString(" Values |")
			sep += "---|"
		}
		if defaults {
			b.WriteString(" Default |")
			sep += "---|"
		}
		b.WriteString(sep + "\n")
		for _, r := range t.Rows {
			fmt.Fprintf(b, "| `%s` | %s |", r.Name, escapePipes(strings.TrimSuffix(r.Takes, ".")))
			if values {
				fmt.Fprintf(b, " %s |", escapePipes(codes(r.Values)))
			}
			if defaults {
				switch {
				case r.Required:
					b.WriteString(" _required_ |")
				case r.Default != "":
					fmt.Fprintf(b, " `%s` |", r.Default)
				default:
					b.WriteString(" |")
				}
			}
			b.WriteString("\n")
		}
	}
	if t.Note != "" {
		fmt.Fprintf(b, "\n%s\n", strings.TrimSpace(t.Note))
	}
}

func codes(values []string) string {
	vs := make([]string, len(values))
	for i, v := range values {
		vs[i] = "`" + v + "`"
	}
	return strings.Join(vs, ", ")
}

func first(values []string, n int) []string {
	if len(values) > n {
		return values[:n]
	}
	return values
}

// ParamsPage renders all parameter types: what each takes, and values it
// takes.
func ParamsPage(reg *match.Registry, frontmatter bool) (string, error) {
	params := reg.Params()
	if len(params) == 0 {
		return "", ErrEmpty
	}
	var b strings.Builder
	if frontmatter {
		b.WriteString("---\ntitle: Parameter types\ndescription: The {placeholders} available in step expressions.\n---\n\n")
	}
	b.WriteString(GeneratedHeader)
	if !frontmatter {
		b.WriteString("\n# Parameter types\n")
	}
	b.WriteString("\n| Parameter | Takes | Values | For example | Pack |\n|---|---|---|---|---|\n")
	for _, p := range params {
		if p.Type.Name == "" {
			continue // the anonymous {}: any text
		}
		fmt.Fprintf(&b, "| `{%s}` | %s | %s | %s | %s |\n", p.Type.Name, escapePipes(strings.TrimSuffix(oneLine(p.Type.Doc), ".")),
			escapePipes(codes(p.Type.Values)), escapePipes(codes(first(p.Type.Examples, 3))), p.Pack)
	}
	return b.String(), nil
}

// StepIndex renders a compact, grep-friendly list: one line per variant.
// Agents load this first to find step text without reading every page.
func StepIndex(reg *match.Registry) (string, error) {
	vs := reg.Variants()
	if len(vs) == 0 {
		return "", ErrEmpty
	}
	var b strings.Builder
	b.WriteString(GeneratedHeader)
	b.WriteString("\n# Step index\n\nEvery step axx understands, one per line: `pack | id | expression`. " +
		"`{name}` is a parameter; see parameter-types.md. Search this file instead of inventing step text.\n\n```text\n")
	lines := make([]string, 0, len(vs))
	for _, v := range vs {
		suffix := ""
		switch v.Def.Step.Arg {
		case core.ArgTable:
			suffix = "  [+table]"
		case core.ArgDocString:
			suffix = "  [+docstring]"
		}
		lines = append(lines, fmt.Sprintf("%s | %s | %s%s", v.Def.Pack, v.Def.Step.ID, v.Expr, suffix))
	}
	b.WriteString(strings.Join(lines, "\n"))
	b.WriteString("\n```\n")
	return b.String(), nil
}

func defsOf(reg *match.Registry, pack string) []*match.Def {
	var out []*match.Def
	for _, d := range reg.Defs() {
		if d.Pack == pack {
			out = append(out, d)
		}
	}
	return out
}

func variantsByDef(reg *match.Registry) map[*match.Def][]string {
	out := map[*match.Def][]string{}
	for _, v := range reg.Variants() {
		out[v.Def] = append(out[v.Def], v.Expr)
	}
	for _, vs := range out {
		sort.SliceStable(vs, func(i, j int) bool { return len(vs[i]) < len(vs[j]) })
	}
	return out
}

func paramDocs(reg *match.Registry) map[string]core.ParamType {
	out := map[string]core.ParamType{}
	for _, p := range reg.Params() {
		out[p.Type.Name] = p.Type
	}
	return out
}

func oneLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.Index(s, "\n\n"); i > 0 {
		s = s[:i]
	}
	return strings.Join(strings.Fields(s), " ")
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
