// Package md renders axx's generated reference documentation as Markdown.
//
// The same renderer feeds the documentation site, the agent skills and
// `axx steps --format md`, so they can never disagree. Every renderer
// returns an error rather than empty output: an empty step reference is a
// bug, not a valid document.
package md

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/nimbusxr/axx/core"
	"github.com/nimbusxr/axx/internal/match"
)

// GeneratedHeader marks generated files; CI fails when they drift.
const GeneratedHeader = "<!-- Code generated by `axx docs export`. DO NOT EDIT. -->\n"

// ErrEmpty is returned when a renderer would produce an empty document.
var ErrEmpty = errors.New("refusing to render an empty reference")

// PackInfo describes a pack for rendering.
type PackInfo struct {
	Name     string
	Manifest core.Manifest
}

// StepsPage renders the reference page for one pack.
func StepsPage(reg *match.Registry, p PackInfo, frontmatter bool) (string, error) {
	defs := defsOf(reg, p.Name)
	if len(defs) == 0 {
		return "", fmt.Errorf("pack %s: %w", p.Name, ErrEmpty)
	}
	var b strings.Builder
	if frontmatter {
		fmt.Fprintf(&b, "---\ntitle: %s steps\ndescription: %q\n---\n\n", p.Name, oneLine(p.Manifest.Doc))
	}
	b.WriteString(GeneratedHeader)
	if !frontmatter {
		fmt.Fprintf(&b, "\n# %s steps\n", p.Name)
	}
	if p.Manifest.Doc != "" {
		fmt.Fprintf(&b, "\n%s\n", strings.TrimSpace(p.Manifest.Doc))
	}
	variants := variantsByDef(reg)
	params := paramDocs(reg)
	for _, d := range defs {
		writeStep(&b, d, variants[d], params)
	}
	return b.String(), nil
}

func writeStep(b *strings.Builder, d *match.Def, variants []string, params map[string]string) {
	s := d.Step
	fmt.Fprintf(b, "\n## `%s`\n\n", s.ID)
	if s.DeprecatedBy != "" {
		fmt.Fprintf(b, "> **Deprecated:** %s\n\n", s.DeprecatedBy)
	}
	kw := s.Keyword
	if kw == "" {
		kw = "*"
	}
	fmt.Fprintf(b, "```gherkin\n%s %s\n", kw, s.Expr)
	switch s.Arg {
	case core.ArgTable:
		b.WriteString("  | ... | ... |\n")
	case core.ArgDocString:
		b.WriteString("  \"\"\"\n  ...\n  \"\"\"\n")
	}
	b.WriteString("```\n")
	if s.Doc != "" {
		fmt.Fprintf(b, "\n%s\n", strings.TrimSpace(s.Doc))
	}
	if len(variants) > 1 {
		b.WriteString("\n**Variants** (optional parts in `[[...]]` above):\n\n")
		for _, v := range variants {
			fmt.Fprintf(b, "- `%s`\n", v)
		}
	}
	seen := map[string]bool{}
	var used []string
	for _, n := range d.Names {
		if !seen[n] {
			seen[n] = true
			used = append(used, n)
		}
	}
	if len(used) > 0 {
		b.WriteString("\n**Parameters:** ")
		for i, n := range used {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "`{%s}`", n)
			if doc := params[n]; doc != "" {
				fmt.Fprintf(b, " (%s)", strings.TrimSuffix(oneLine(doc), "."))
			}
		}
		b.WriteString("\n")
	}
	if len(s.Examples) > 0 {
		b.WriteString("\n**Example:**\n\n```gherkin\n")
		for _, ex := range s.Examples {
			b.WriteString(ex + "\n")
		}
		b.WriteString("```\n")
	}
	if s.Since != "" {
		fmt.Fprintf(b, "\n_Since %s._\n", s.Since)
	}
}

// ParamsPage renders all parameter types.
func ParamsPage(reg *match.Registry, frontmatter bool) (string, error) {
	params := reg.Params()
	if len(params) == 0 {
		return "", ErrEmpty
	}
	var b strings.Builder
	if frontmatter {
		b.WriteString("---\ntitle: Parameter types\ndescription: The {placeholders} available in step expressions.\n---\n\n")
	}
	b.WriteString(GeneratedHeader)
	if !frontmatter {
		b.WriteString("\n# Parameter types\n")
	}
	b.WriteString("\n| Parameter | Matches | Description | Provided by |\n|---|---|---|---|\n")
	for _, p := range params {
		name := p.Type.Name
		if name == "" {
			name = "(anonymous)"
		}
		fmt.Fprintf(&b, "| `{%s}` | `%s` | %s | %s |\n", name, escapePipes(strings.Join(p.Type.Regexps, "` or `")), escapePipes(oneLine(p.Type.Doc)), p.Pack)
	}
	return b.String(), nil
}

// StepIndex renders a compact, grep-friendly list: one line per variant.
// Agents load this first to find step text without reading every page.
func StepIndex(reg *match.Registry) (string, error) {
	vs := reg.Variants()
	if len(vs) == 0 {
		return "", ErrEmpty
	}
	var b strings.Builder
	b.WriteString(GeneratedHeader)
	b.WriteString("\n# Step index\n\nEvery step axx understands, one per line: `pack | id | expression`. " +
		"`{name}` is a parameter; see parameter-types.md. Search this file instead of inventing step text.\n\n```text\n")
	lines := make([]string, 0, len(vs))
	for _, v := range vs {
		suffix := ""
		switch v.Def.Step.Arg {
		case core.ArgTable:
			suffix = "  [+table]"
		case core.ArgDocString:
			suffix = "  [+docstring]"
		}
		lines = append(lines, fmt.Sprintf("%s | %s | %s%s", v.Def.Pack, v.Def.Step.ID, v.Expr, suffix))
	}
	b.WriteString(strings.Join(lines, "\n"))
	b.WriteString("\n```\n")
	return b.String(), nil
}

func defsOf(reg *match.Registry, pack string) []*match.Def {
	var out []*match.Def
	for _, d := range reg.Defs() {
		if d.Pack == pack {
			out = append(out, d)
		}
	}
	return out
}

func variantsByDef(reg *match.Registry) map[*match.Def][]string {
	out := map[*match.Def][]string{}
	for _, v := range reg.Variants() {
		out[v.Def] = append(out[v.Def], v.Expr)
	}
	for _, vs := range out {
		sort.SliceStable(vs, func(i, j int) bool { return len(vs[i]) < len(vs[j]) })
	}
	return out
}

func paramDocs(reg *match.Registry) map[string]string {
	out := map[string]string{}
	for _, p := range reg.Params() {
		out[p.Type.Name] = p.Type.Doc
	}
	return out
}

func oneLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.Index(s, "\n\n"); i > 0 {
		s = s[:i]
	}
	return strings.Join(strings.Fields(s), " ")
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
