// SPDX-License-Identifier: Apache-2.0

// axx: the IntelliJ companion plugin for axx. It runs the axx language server (`axx lsp`) for
// .feature files, runs scenarios in the IDE's test runner (axx run configurations), and when an
// axx run in the IDE asks for a debugger ([AXX-IDE] marker lines), it starts the matching
// "Debugger: <app>" run configuration.
// Standalone build: see settings.gradle.kts.
plugins {
    java
    id("org.jetbrains.intellij.platform") version "2.19.0"
}

group = "us.nimbusxr.axx"
version = providers.gradleProperty("pluginVersion").get()

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea(providers.gradleProperty("platformVersion"))
        // Not bundled with the IDE, and an optional dependency: the plugin compiles against its
        // step PSI (go to declaration), and runIde and the tests get it installed.
        plugin("gherkin", providers.gradleProperty("gherkinVersion").get())
        // For the tests that run in a headless IDE.
        testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform)
        // The platform's remote debug configuration, which Go Remote extends: AxxRunStateTest
        // stands in for the Go plugin with it.
        testBundledModule("intellij.platform.scriptDebugger.ui")
    }

    testImplementation(platform("org.junit:junit-bom:6.1.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // AxxLspIntegrationTest is a JUnit 3 style platform test, run by the vintage engine. The
    // platform's test class loader needs JUnit 4 for the JUnit 5 tests too (IJPL-159134).
    testImplementation("junit:junit:4.13.2")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine")
    // The platform test framework needs it and does not bring it (IJPL-157292).
    testImplementation("org.opentest4j:opentest4j:1.3.0")
}

// `./gradlew runIdeWithGo`: the sandbox IDE with the Go plugin, to debug step
// code (`axx run --debug-steps` attaches a Go Remote debugger). The Go plugin
// needs an IntelliJ IDEA subscription: sign in once in the sandbox.
intellijPlatformTesting {
    runIde {
        register("runIdeWithGo") {
            plugins {
                plugin("org.jetbrains.plugins.go", providers.gradleProperty("goPluginVersion").get())
            }
        }
    }
}

intellijPlatform {
    // No GUI forms or @NotNull instrumentation needed; skipping avoids resolving the
    // java-compiler-ant-tasks artifact.
    instrumentCode = false
    // The one settings page (Settings | Tools | axx) has a single field, not worth indexing for
    // settings search (and this spares starting a headless IDE during the build).
    buildSearchableOptions = false

    pluginConfiguration {
        id = "us.nimbusxr.axx.idea"
        name = "axx"
        version = project.version.toString()
        description =
            """
            Support for <a href="https://github.com/nimbusxr/axx">axx</a> acceptance tests.
            <ul>
              <li><b>Feature files.</b> In projects with an <code>axx.yaml</code>, runs the axx
              language server (<code>axx lsp</code>) for <code>.feature</code> files: step
              completion, step documentation on hover, go to a step's definition, links to, path
              completion for and checks of the files steps name, highlighted step parameters,
              and diagnostics for undefined or ambiguous steps and Gherkin syntax errors. The Gherkin plugin no longer reports axx steps as undefined there. Needs the
              <code>axx</code> executable (found on <code>PATH</code> or where axx's installers
              put it, or set in <i>Settings | Tools | axx</i>) and an IDE that includes the LSP
              API, as IntelliJ IDEA does.</li>
              <li><b>Running scenarios.</b> Run and debug icons in the gutter of Feature, Rule,
              Scenario and Scenario Outline lines and Examples rows, and in the context menu of
              feature files and directories; the results show in the IDE's test runner, with
              navigation to each line, expected and actual values of failed assertions, and
              <i>Rerun Failed Tests</i>. Debugging stops at breakpoints in step code with GoLand or
              the Go plugin.</li>
              <li><b>Debugging apps.</b> When <code>axx run --debug</code>, run from the IDE,
              starts a service in debug mode, the plugin starts the matching
              <code>Debugger: &lt;service&gt;</code> run configuration (generated by
              <code>axx ide intellij</code>), so the services under test attach to the IDE with no
              manual steps. The debuggers it started stop again when the run ends.</li>
            </ul>
            """.trimIndent()
        vendor {
            name = "NimbusXR"
            url = "https://github.com/nimbusxr/axx"
        }
        ideaVersion {
            sinceBuild = providers.gradleProperty("sinceBuild")
            // Open-ended: the execution APIs are long-stable, and the LSP API classes the plugin
            // uses (LspServerSupportProvider and friends) stay available, deprecated, after their
            // 2026.1.4 renaming. verifyPlugin checks newer IDEs.
            untilBuild = provider { null }
        }
    }

    // Release credentials come from the environment (see .github/workflows/intellij-plugin.yml).
    signing {
        certificateChain = providers.environmentVariable("CERTIFICATE_CHAIN")
        privateKey = providers.environmentVariable("PRIVATE_KEY")
        password = providers.environmentVariable("PRIVATE_KEY_PASSWORD")
    }
    publishing {
        token = providers.environmentVariable("PUBLISH_TOKEN")
    }

    pluginVerification {
        ides {
            recommended()
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

tasks.test {
    useJUnitPlatform()
    // AxxLspIntegrationTest runs only with AXX_BIN set (an axx binary with `axx lsp`), so its value
    // is a test input: setting it reruns the tests instead of reusing an earlier result.
    inputs.property("axxBin", providers.environmentVariable("AXX_BIN").orElse(""))
}
